[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"
log = "0.4.20"
num = "0.4.1"
quit = "2.0.0"
rayon = "1.8.0"
regex = "1.10.2"
simple_logger = "4.3.0"
